### Create chapter
POST http://localhost:8080/api/v1/chapters
Content-Type: application/json

{
  "description": "NEW DESCRIPTION",
  "title": "NEW TITLE",
  "courseId": "057f5ffc-01d3-4f65-a67b-accd42e64d7d"
}


### Get all chapters
GET http://localhost:8080/api/v1/chapters
Content-Type: application/json

### Get chapter by id
GET http://localhost:8080/api/v1/chapters/7c0a1442-0e83-4d7c-8242-72a03f5bac28
Content-Type: application/json

### Update chapter
PUT http://localhost:8080/api/v1/chapters/7c0a1442-0e83-4d7c-8242-72a03f5bac28
Content-Type: application/json

{
  "description": "UPDATED DESCRIPTION",
  "title": "UPDATED TITLE"
}

### Add section to chapter
PUT http://localhost:8080/api/v1/chapters/move-section-to/7c0a1442-0e83-4d7c-8242-72a03f5bac28/aaab4afa-732b-4d45-a5ca-1f6f234aa762
Content-Type: application/json


### Remove section from chapter
DELETE http://localhost:8080/api/v1/chapters/7c0a1442-0e83-4d7c-8242-72a03f5bac28/remove-section/aaab4afa-732b-4d45-a5ca-1f6f234aa762


### Remove chapter
DELETE http://localhost:8080/api/v1/chapters/e29061d6-285b-4ecb-90a1-38178a8aa851

