### Create a new User
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Stivi",
  "lastName": "Dragiev",
  "email": "test@example.com",
  "profilePicUrl": "/images/profile.png"
}

### Get all users
GET http://localhost:8080/api/v1/users
Accept: application/json


### Get single user
GET http://localhost:8080/api/v1/users/ef0eed29-eb71-4f86-8e91-d771e873aab1
Accept: application/json


### Unenroll in a course
PUT http://localhost:8080/api/v1/users/ef0eed29-eb71-4f86-8e91-d771e873aab1/unenroll/2f08d30a-4a54-41f0-acd1-1c78fb5e8a43
Accept: application/json


### Enroll in a course
PUT http://localhost:8080/api/v1/users/ef0eed29-eb71-4f86-8e91-d771e873aab1/enroll/2f08d30a-4a54-41f0-acd1-1c78fb5e8a43
Accept: application/json


### Delete a user
DELETE http://localhost:8080/api/v1/users/ef0eed29-eb71-4f86-8e91-d771e873aab1