### Create a new problem
POST http://localhost:8080/api/v1/problems
Content-Type: application/json

{
  "description": "DESCRIPTION",
  "solution": "SOLUTION",
  "solutionType": "NUMERICAL",
  "isChallenge": false,
  "points": 100
}


### Get existing problems
GET http://localhost:8080/api/v1/problems
Content-Type: application/json

### Get an existing problem
GET http://localhost:8080/api/v1/problems/f8c626df-dfcc-4b31-8bda-9e9aaa8ec145
Content-Type: application/json


### Updates an existing problem
PUT http://localhost:8080/api/v1/problems/88ad103e-4ff1-4b9b-8653-a35126128433
Content-Type: application/json

{
  "solutionType": "EXPRESSION",
  "isChallenge": false,
  "points": 0
}

### Adds a tag to an existing problem
PUT http://localhost:8080/api/v1/problems/88ad103e-4ff1-4b9b-8653-a35126128433/add-tag/757fbbc4-29f4-40fa-90cf-5eba3d39bd28
Content-Type: application/json


### Removes a tag appended to an existing problem
DELETE http://localhost:8080/api/v1/problems/88ad103e-4ff1-4b9b-8653-a35126128433/remove-tag/757fbbc4-29f4-40fa-90cf-5eba3d39bd28
Content-Type: application/json

### Deletes a problem
DELETE http://localhost:8080/api/v1/problems/88ad103e-4ff1-4b9b-8653-a35126128433
Content-Type: application/json