### Create new page.
POST http://localhost:8080/api/v1/pages
Content-Type: application/json

{
  "content": "CONTENT",
  "position": 1
}


### Get existing page
GET http://localhost:8080/api/v1/pages/70e57384-008e-4c7c-9666-96f3d0eb2ac4
Content-Type: application/json


### Get all pages
GET http://localhost:8080/api/v1/pages
Content-Type: application/json


### Update page
PUT http://localhost:8080/api/v1/pages/e9c12909-70d0-4d3b-b26c-b5b99b9d78c1
Content-Type: application/json

{
  "content": "NEW"
}

### Add problem
PUT http://localhost:8080/api/v1/pages/309681c4-dfeb-4fa3-a653-03bc22e52c0a/add-problem/f8c626df-dfcc-4b31-8bda-9e9aaa8ec145
Content-Type: application/json

{
  "problemType": "HOMEWORK"
}


### Remove problem from existing page.
DELETE http://localhost:8080/api/v1/pages/e9c12909-70d0-4d3b-b26c-b5b99b9d78c1/remove-problem/f8c626df-dfcc-4b31-8bda-9e9aaa8ec145
Content-Type: application/json

### Delete a page
DELETE http://localhost:8080/api/v1/pages/e9c12909-70d0-4d3b-b26c-b5b99b9d78c1
Content-Type: application/json
