### Create new Section
POST http://localhost:8080/api/v1/sections
Content-Type: application/json

{
  "title": "TITLE",
  "description": "DESCRIPTION",
  "chapterId": "ad98c02c-d099-4fde-a570-22eebf9d97d0"
}



### Get all existing sections
GET http://localhost:8080/api/v1/sections
Content-Type: application/json

### Get an existing section
GET http://localhost:8080/api/v1/sections/f616916a-fbd7-4d12-b389-d7244e036f51
Content-Type: application/json


### Update a section
PUT http://localhost:8080/api/v1/sections/f616916a-fbd7-4d12-b389-d7244e036f51
Content-Type: application/json

{
  "title": "UPDATED",
  "description": "UPDATED"
}

### Add new page
PUT http://localhost:8080/api/v1/sections/f616916a-fbd7-4d12-b389-d7244e036f51/add-page/309681c4-dfeb-4fa3-a653-03bc22e52c0a
Content-Type: application/json


### Remove page from section
DELETE http://localhost:8080/api/v1/sections/f616916a-fbd7-4d12-b389-d7244e036f51/remove-page/309681c4-dfeb-4fa3-a653-03bc22e52c0a
Content-Type: application/json

### Remove section
DELETE http://localhost:8080/api/v1/sections/f616916a-fbd7-4d12-b389-d7244e036f51
Content-Type: application/json